
services:
  postgres:
    image: postgres:15-alpine
    container_name: fintech_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${POSTGRES_DB:-fintech_nodejs_db}
    ports:
      - "5433:5432"  # <host_port>:<container_port>: Changed host port from 5432 to 5433 to avoid conflict with local PostgreSQL db service
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: fintech_api
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:


  # Command Breakdown

  # docker-compose up: Reads the docker-compose.yml file, creates the network, provisions volumes and starts all defined services 
  # (postgres and api).

  # --build: Forces Docker to build (or rebuild) the container image using your Dockerfile before starting the container. 
  # This ensures any recent changes to your Node.js code or package.json are freshly compiled into the image rather than using a cached version.
  
  # -d (Detached Mode): Runs the containers silently in the background and returns control of your terminal prompt back to you.
  
  # Sequence
  # 1. Spins up PostgreSQL (postgres service): 
  # - Downloads the postgres:15-alpine image if not already cached. 
  # - Creates a dedicated database volume (pgdata) so your data persists even if the container stops.
  # - Listens for readiness via the PostgreSQL health check (pg_isready).
  # 2. Builds & Runs your API (api service):
  # - Reads your Dockerfile, installs production dependencies and generates Prisma client bindings inside the container.
  # - Waits for PostgreSQL to pass its health check before starting.
  # - Runs npx prisma migrate deploy automatically to apply database schemas.
  # - Launches node src/index.js on port 5000.
  
  # Docker Commands for Development
  # docker-compose logs -f api: Stream live console logs from your Express API
  # docker-compose ps: Check status/health of all running containers
  # docker-compose: downStop and remove the containers (keeps DB data intact)
  # docker-compose down -v: Stop containers and wipe database volumes (fresh state)

  # docker compose logs postgres

  # (Note: Use port 5432 inside DATABASE_URL because api talks to postgres on Docker's internal network. Port 5433 is only for host-machine connections like DBeaver or PgAdmin).